import { StyleSheet } from "react-native";

import { SpendWiseTheme } from "@/theme/spendwise";

export const feedbackStyles = StyleSheet.create({
  content: {
    paddingTop: 116,
    paddingBottom: 36,
    gap: 18,
  },
  pageTitle: {
    color: SpendWiseTheme.colors.text,
    fontSize: 34,
    fontWeight: "800",
  },
  heroCard: {
    borderRadius: 30,
    backgroundColor: "rgba(255,255,255,0.70)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.42)",
    padding: 20,
    gap: 10,
  },
  heroText: {
    color: SpendWiseTheme.colors.textMuted,
    fontSize: 15,
    lineHeight: 22,
  },
  signalRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 4,
  },
  signalPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,253,231,0.88)",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  signalText: {
    color: SpendWiseTheme.colors.text,
    fontSize: 13,
    fontWeight: "700",
  },
  formCard: {
    borderRadius: 30,
    backgroundColor: "rgba(255,255,255,0.66)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.38)",
    padding: 20,
    gap: 14,
  },
  cardTitle: {
    color: SpendWiseTheme.colors.text,
    fontSize: 28,
    fontWeight: "800",
  },
  cardCaption: {
    color: SpendWiseTheme.colors.textMuted,
    fontSize: 14,
    lineHeight: 21,
  },
  infoPanel: {
    borderRadius: 20,
    backgroundColor: "rgba(255,253,231,0.88)",
    padding: 16,
    gap: 10,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  infoLabel: {
    flex: 1,
    color: SpendWiseTheme.colors.textMuted,
    fontSize: 13,
    fontWeight: "700",
  },
  infoValue: {
    color: SpendWiseTheme.colors.text,
    fontSize: 14,
    fontWeight: "800",
    textAlign: "right",
  },
  fieldLabel: {
    color: SpendWiseTheme.colors.text,
    fontSize: 16,
    fontWeight: "800",
  },
  input: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(122,136,195,0.36)",
    backgroundColor: "rgba(255,255,255,0.74)",
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: SpendWiseTheme.colors.text,
    fontSize: 16,
  },
  messageInput: {
    minHeight: 138,
    textAlignVertical: "top",
  },
  starRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  starButton: {
    flex: 1,
    minHeight: 56,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.70)",
    borderWidth: 1,
    borderColor: "rgba(122,136,195,0.26)",
    alignItems: "center",
    justifyContent: "center",
  },
  starButtonActive: {
    backgroundColor: "rgba(255,245,157,0.94)",
    borderColor: "rgba(255,245,157,1)",
  },
  ratingSummaryCard: {
    borderRadius: 18,
    backgroundColor: "rgba(255,253,231,0.84)",
    padding: 16,
    gap: 6,
  },
  ratingTitle: {
    color: SpendWiseTheme.colors.text,
    fontSize: 16,
    fontWeight: "800",
  },
  ratingText: {
    color: SpendWiseTheme.colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  metaText: {
    color: SpendWiseTheme.colors.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  actionRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 4,
  },
  ghostButton: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: "#FFFBE0",
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  ghostButtonText: {
    color: SpendWiseTheme.colors.text,
    fontSize: 16,
    fontWeight: "700",
  },
  submitButton: {
    flex: 1.25,
    borderRadius: 18,
    backgroundColor: SpendWiseTheme.colors.text,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  submitText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "800",
  },
  aboutCard: {
    borderRadius: 30,
    backgroundColor: "rgba(255,255,255,0.68)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.38)",
    padding: 22,
    gap: 14,
  },
  aboutTitle: {
    fontSize: 30,
    fontWeight: "800",
    color: "#000000",
  },
  aboutSubtitle: {
    color: SpendWiseTheme.colors.textMuted,
    fontSize: 14,
    fontWeight: "700",
  },
  aboutText: {
    color: SpendWiseTheme.colors.text,
    fontSize: 15,
    lineHeight: 23,
  },
  highlightList: {
    gap: 10,
  },
  highlightRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  highlightText: {
    flex: 1,
    color: SpendWiseTheme.colors.text,
    fontSize: 14,
    fontWeight: "700",
  },
  signatureCard: {
    borderRadius: 20,
    backgroundColor: "rgba(255,253,231,0.88)",
    padding: 16,
    gap: 10,
  },
});
